export const GET_ALL_COMPANYS = "GET_ALL_COMPANYS"
export const GET_ALL_PRODUCT = "GET_ALL_PRODUCT"
export const GET_ALL_VACANTS = "GET_ALL_VACANTS"
export const GET_ALL_USERS = "GET_ALL_USERS"
export const GET_ALL_PAYMETHOD = "GET_ALL_PAYMETHOD" 

export const CLEAN_DETAIL = "CLEAN_DETAIL"

export const GET_COMPANY_DETAIL = "GET_COMPANY_DETAIL"
export const GET_VACANT_DETAIL="GET_VACANT_DETAIL"
export const GET_USERS_DETAIL = "GET_USERS_DETAIL"

export const GET_ALL_CV = "GET_ALL_CV"
export const GET_CV_BY_ID = "GET_CV_BY_ID"


export const GET_EMAIL = "GET_EMAIL"

export const POST_USER = "POST_USER"
export const POST_COMPANY = "POST_COMPANY"
export const POST_OPERATION_DETAIL = "POST_OPERATION_DETAIL"
export const POST_VACANT = "POST_VACANT"
export const POST_CV = "POST_CV"
export const POST_EXPE = "POST_EXPE"
export const POST_FORMAITON = "POST_FORMAITON"
export const POST_STARS = "POST_STARS"

export const POST_OPERATION = "POST_OPERATION"

export const POST_RELATION_VACANT_APPLICANT = "POST_RELATION_VACANT_APPLICANT"



export const FILTER_PER_SENIORITY = "FILTER_PER_SENIORITY"
export const FILTER_PER_WORDKMETHOD = "FILTER_PER_WORDKMETHOD"
export const FILTER_PER_TIME = "FILTER_PER_TIME"


export const FIND_PER_NAME="FIND_PER_NAME"

export const LOGIN = "LOGIN"
export const LOGIN_APPLICANT = "LOGIN_APPLICANT"
export const LOGIN_COMPANY = "LOGIN_COMPANY"